name: publish

on:
    push:
        branches: [ main ]

env:
    DOTNET_VERSION: '8.0.123' # The .NET SDK version to use

jobs:
    publish:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Build
              run: |
                  ./release.sh
            - uses: pipe-cd/actions-gh-release@v2.3.4
              with:
                  release_file: 'KeyzAllowUtils.zip'
                  token: ${{ secrets.GITHUB_TOKEN }}
